name: CI/CD

# workflow triggers
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-build:
    name: Test 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: run build
        run: npm run build  
        env:
          VITE_APP_PUBLIC_URL: ${{ github.repository }}
      - name: uploading build files
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
         name: artifact
         path: ./dist

  deploy:
      name: Deploy
      runs-on: ubuntu-latest
      needs: test-build
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      permissions:
        contents: write
      steps:
      - name: Downloading artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: ./dist
      - name: Deploying to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
